version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BedrockModelId=\"openai.gpt-oss-20b-1:0\" ConfidenceThreshold=\"0.8\" NotificationFromEmail=\"user@example.com\" NotificationToEmail=\"success@simulator.amazonses.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
